#!/bin/bash

# Build docker image
git clone https://github.com/lmb/dokku-peerjs-dockerfiles.git /tmp/dokku-peerjs-dockerfiles
docker build -t peerjs-server /tmp/dokku-peerjs-dockerfiles
rm -rf /tmp/dokku-peerjs-dockerfiles
